---
# tasks file for cornerstone:discover-ip-aws.yml

#
# -----------------------------------------------------------------------------
# Discover Virtual Machine IP Address
# -----------------------------------------------------------------------------
#

# Discover IP Address of VM
- name: "[Cornerstone - VMWARE VM] Discover DNS/IP Address"
  vmware_guest_facts:
    validate_certs: "{{ cornerstone_vmware_validate_certs }}"
    hostname: "{{ cornerstone_vmware_hostname }}"
    username: "{{ cornerstone_vmware_username }}"
    password: "{{ cornerstone_vmware_password }}"
    datacenter: "{{ cornerstone_vmware_datacenter }}"
    folder: "{{ cornerstone_vmware_vcsfolder }}"
    name: "{{ cornerstone_vm_name }}"
  register: vm_data
  tags: ["{{ cornerstone_platform }}"]

# Set DNS/IP Address as Fact
- name: "[Cornerstone - VMWARE VM] Set DNS/IP Address"
  set_fact:
    cornerstone_vm_ipaddress: "{{ vm_data.instance.ipv4 }}"
  tags: ["{{ cornerstone_platform }}"]

- name: "[Cornerstone - VM] Display DNS/IP Address"
  debug:
    msg: "Cornerstone VM IP Address: {{ cornerstone_vm_ipaddress }}"

- name: "[Cornerstone - VM] Register IP with Temporary Host Group"
  add_host:
    hostname: "{{ cornerstone_vm_name }}"
    groupname: "{{ cornerstone_prefix }}"
    ansible_host: "{{ cornerstone_vm_ipaddress }}"

- name: "[Cornerstone - VM] Register IP with Temporary Host Group named after the Purpose tag"
  add_host:
    hostname: "{{ cornerstone_vm_name }}"
    groupname: "{{ cornerstone_tag_purpose }}"
    ansible_host: "{{ cornerstone_vm_ipaddress }}"
  when:
    - cornerstone_tag_purpose != ""

- name: "[Cornerstone - VM] Register IP with Temporary Host Group named after the Role tag"
  add_host:
    hostname: "{{ cornerstone_vm_name }}"
    groupname: "{{ cornerstone_tag_role }}"
    ansible_host: "{{ cornerstone_vm_ipaddress }}"
  when:
    - cornerstone_tag_role != ""

- name: "[Cornerstone - VM] Register IP with Temporary Windows host Group when windows box"
  add_host:
    hostname: "{{ cornerstone_vm_name }}"
    groupname: windows
    ansible_host: "{{ cornerstone_vm_ipaddress }}"
  when:
    - cornerstone_vmware_instance_guest_id == "windows9Server64Guest"
