---
# tasks file for cornerstone:discover-ip-aws.yml

#
# -----------------------------------------------------------------------------
# Discover Virtual Machine IP Address
# -----------------------------------------------------------------------------
#

# Discover IP Address of VM
- name: "[Cornerstone - VMWARE VM] Discover DNS/IP Address"
  vmware_guest_facts:
    validate_certs: "{{ cornerstone_vmware_validate_certs }}"
    hostname: "{{ cornerstone_vmware_hostname }}"
    username: "{{ cornerstone_vmware_username }}"
    password: "{{ cornerstone_vmware_password }}"
    datacenter: "{{ cornerstone_vmware_datacenter }}"
    folder: "{{ cornerstone_vmware_vcsfolder }}"
    name: "{{ cornerstone_vm_name }}"
  register: vm_data
  tags: ["{{ cornerstone_platform }}"]

# Set DNS/IP Address as Fact
- name: "[Cornerstone - VMWARE VM] Set DNS/IP Address"
  set_fact:
      cornerstone_vm_ipaddress: "{{ vm_data.ipv4 }}"
  tags: ["{{ cornerstone_platform }}"]

- name: "[Cornerstone - VM] Display DNS/IP Address"
  debug:
    msg: "Cornerstone VM IP Address: {{ cornerstone_vm_ipaddress }}"

- name: "[Cornerstone - VM] Register IP with Temporary Host Group"
  add_host:
    hostname: "{{ cornerstone_vm_ipaddress }}"
    groupname: "{{ cornerstone_prefix }}"
    ansible_ssh_user: "{{ cornerstone_ssh_user }}"
    ansible_ssh_private_key_file: "{{ cornerstone_ssh_key_path }}"
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'

- name: "[Cornerstone - VM] Register IP with Temporary Host Group named after the Purpose tag"
  add_host:
    hostname: "{{ cornerstone_vm_ipaddress }}"
    groupname: "{{ cornerstone_tag_purpose }}"
    ansible_ssh_user: "{{ cornerstone_ssh_user }}"
    ansible_ssh_private_key_file: "{{ cornerstone_ssh_key_path }}"
    ansible_ssh_extra_args: "{{ cornerstone_ssh_extra_args }}"
  when:   
    - cornerstone_tag_purpose != ""

- name: "[Cornerstone - VM] Register IP with Temporary Host Group named after the Role tag"
  add_host:
    hostname: "{{ cornerstone_vm_ipaddress }}"
    groupname: "{{ cornerstone_tag_role }}"
    ansible_ssh_user: "{{ cornerstone_ssh_user }}" 
    ansible_ssh_private_key_file: "{{ cornerstone_ssh_key_path }}"
    ansible_ssh_extra_args: "{{ cornerstone_ssh_extra_args }}"
  when:
    - cornerstone_tag_role != ""
