---
# tasks file for cornerstone

#
# -----------------------------------------------------------------------------
# Common Tasks
# -----------------------------------------------------------------------------
#
- include: common-{{ cornerstone_platform }}.yml
  tags: [common, "{{ cornerstone_platform }}"]
  when:
    - cornerstone_platform != 'libvirt'
    - cornerstone_platform != 'vmware'

#
# -----------------------------------------------------------------------------
# Network Tasks
# -----------------------------------------------------------------------------
#
- include: network-{{ cornerstone_platform }}.yml
  tags: [network, "{{ cornerstone_platform }}"]
  when:
    - cornerstone_platform != 'libvirt'
    - cornerstone_platform != 'vmware'

#
# -----------------------------------------------------------------------------
# Virtual Machine Tasks
# -----------------------------------------------------------------------------
#
#  include: "vm-{{ item.value.cornerstone_platform }}.yml"

- name: Build vms based on dict
  include_tasks: "vm-{{ item.value.cornerstone_platform }}.yml"
  vars:
    cornerstone_platform: "{{ item.value.cornerstone_platform }}"
    cornerstone_tag_purpose: "{{ item.value.cornerstone_tag_purpose }}"
    cornerstone_tag_role: "{{ item.value.cornerstone_tag_role }}"
    cornerstone_vm_name: "{{ item.value.cornerstone_vm_name }}"
    cornerstone_vm_state: "{{ item.value.cornerstone_vm_state }}"
    cornerstone_location: "{{ item.value.cornerstone_location }}"
    cornerstone_vm_aws_az: "{{ item.value.cornerstone_vm_aws_az }}"
    cornerstone_vm_flavour: "{{ item.value.cornerstone_vm_flavour }}"
    cornerstone_vm_aws_ami: "{{ item.value.cornerstone_vm_aws_ami }}"
    cornerstone_vm_aws_sg: "{{ item.value.cornerstone_vm_aws_sg }}"
    cornerstone_virtual_network_name: "{{ item.value.cornerstone_virtual_network_name }}"
    cornerstone_virtual_network_cidr: "{{ item.value.cornerstone_virtual_network_cidr }}"
    cornerstone_subnet_name: "{{ item.value.cornerstone_subnet_name }}"
    cornerstone_vm_assign_public_ip: "{{ item.value.cornerstone_vm_assign_public_ip }}"
    cornerstone_vm_public_ip: "{{ item.value.cornerstone_vm_public_ip }}"
    cornerstone_public_private_ip: "{{ item.value.cornerstone_public_private_ip }}"
    cornerstone_publicip_allocation_method: "{{ item.value.cornerstone_publicip_allocation_method }}"
    cornerstone_publicip_domain_name: "{{ item.value.cornerstone_publicip_domain_name }}"
    cornerstone_public_private_domain_name: "{{ item.value.cornerstone_public_private_domain_name }}"
    cornerstone_vm_os_disk_size: "{{ item.value.cornerstone_vm_os_disk_size }}"
    cornerstone_vm_data_disk: "{{ item.value.cornerstone_vm_data_disk }}"
    cornerstone_vm_data_disk_device_name: "{{ item.value.cornerstone_vm_data_disk_device_name }}"
    cornerstone_aws_vm_data_disk_managed: "{{ item.value.cornerstone_aws_vm_data_disk_managed }}"
    cornerstone_vm_data_disk_size: "{{ item.value.cornerstone_vm_data_disk_size }}"
    cornerstone_vm_location: "{{ item.value.cornerstone_vm_location }}"
    cornerstone_working_dir: "{{ item.value.cornerstone_working_dir }}"
    cornerstone_vm_libvirt_template: "{{ item.value.cornerstone_vm_libvirt_template }}"
    cornerstone_vm_libvirt_file_type: "{{ item.value.cornerstone_vm_libvirt_file_type }}"
    cornerstone_vm_libvirt_vmtype: "{{ item.value.cornerstone_vm_libvirt_vmtype }}"
    cornerstone_vm_libvirt_vmos: "{{ item.value.cornerstone_vm_libvirt_vmos }}"
    cornerstone_vm_libvirt_vmmem: "{{ item.value.cornerstone_vm_libvirt_vmmem }}"
    cornerstone_vm_libvirt_vmcores: "{{ item.value.cornerstone_vm_libvirt_vmcores }}"
    cornerstone_vm_subnet: "{{ item.value.cornerstone_vm_subnet }}" 
    cornerstone_vm_gateway: "{{ item.value.cornerstone_vm_gateway }}"
    cornerstone_vm_ip: "{{ item.value.cornerstone_vm_ip }}"
    cornerstone_vmware_validate_certs: "{{ item.value.cornerstone_vmware_validate_certs }}"
    cornerstone_vmware_hostname: "{{ item.value.cornerstone_vmware_hostname }}"
    cornerstone_vmware_username: "{{ item.value.cornerstone_vmware_username }}"
    cornerstone_vmware_password: "{{ item.value.cornerstone_vmware_password }}"
    cornerstone_vmware_datacenter: "{{ item.value.cornerstone_vmware_datacenter }}"
    cornerstone_vmware_cluster: "{{ item.value.cornerstone_vmware_cluster }}"
    cornerstone_vmware_vmtemplate: "{{ item.value.cornerstone_vmware_vmtemplate }}"
    cornerstone_vmware_vcsfolder: "{{ item.value.cornerstone_vmware_vcsfolder }}"
    cornerstone_vmware_datastore: "{{ item.value.cornerstone_vmware_datastore }}"
    cornerstone_vmware_instance_guest_id: "{{ item.value.cornerstone_vmware_instance_guest_id }}"
    cornerstone_vmware_memory: "{{ item.value.cornerstone_vmware_memory }}"
    cornerstone_vmware_cores: "{{ item.value.cornerstone_vmware_cores }}"
    cornerstone_vmware_scsitype: "{{ item.value.cornerstone_vmware_scsitype }}"
    cornerstone_vmware_disks: "{{ item.value.cornerstone_vmware_disks }}"
    cornerstone_vmware_network_name: "{{ item.value.cornerstone_vmware_network_name }}"
    cornerstone_vmware_netmask: "{{ item.value.cornerstone_vmware_netmask }}"
    cornerstone_vmware_dns_servers: "{{ item.value.cornerstone_vmware_dns_servers }}"
    cornerstone_vmware_dvswitch_name: "{{ item.value.cornerstone_vmware_dvswitch_name }}"
    cornerstone_vmware_customization: "{{ item.value.cornerstone_vmware_customization }}"
  with_dict: "{{ guests }}"  
  tags: [vm, "{{ cornerstone_platform }}"]


#
# -----------------------------------------------------------------------------
# Discover IP Address Tasks
# -----------------------------------------------------------------------------
#
- name: Discover IP address tasks
  include: discover-ip-{{ cornerstone_platform }}.yml
  vars:
    cornerstone_platform: "{{ item.value.cornerstone_platform }}"
    cornerstone_tag_purpose: "{{ item.value.cornerstone_tag_purpose }}"
    cornerstone_tag_role: "{{ item.value.cornerstone_tag_role }}"
    cornerstone_vm_name: "{{ item.value.cornerstone_vm_name }}"
    cornerstone_vm_state: "{{ item.value.cornerstone_vm_state }}"
    cornerstone_location: "{{ item.value.cornerstone_location }}"
    cornerstone_vm_aws_az: "{{ item.value.cornerstone_vm_aws_az }}"
    cornerstone_vm_flavour: "{{ item.value.cornerstone_vm_flavour }}"
    cornerstone_vm_aws_ami: "{{ item.value.cornerstone_vm_aws_ami }}"
    cornerstone_vm_aws_sg: "{{ item.value.cornerstone_vm_aws_sg }}"
    cornerstone_virtual_network_name: "{{ item.value.cornerstone_virtual_network_name }}"
    cornerstone_virtual_network_cidr: "{{ item.value.cornerstone_virtual_network_cidr }}"
    cornerstone_subnet_name: "{{ item.value.cornerstone_subnet_name }}"
    cornerstone_vm_assign_public_ip: "{{ item.value.cornerstone_vm_assign_public_ip }}"
    cornerstone_vm_public_ip: "{{ item.value.cornerstone_vm_public_ip }}"
    cornerstone_public_private_ip: "{{ item.value.cornerstone_public_private_ip }}"
    cornerstone_publicip_allocation_method: "{{ item.value.cornerstone_publicip_allocation_method }}"
    cornerstone_publicip_domain_name: "{{ item.value.cornerstone_publicip_domain_name }}"
    cornerstone_vm_data_disk: "{{ item.value.cornerstone_vm_data_disk }}"
    cornerstone_vm_data_disk_device_name: "{{ item.value.cornerstone_vm_data_disk_device_name }}"
    cornerstone_aws_vm_data_disk_managed: "{{ item.value.cornerstone_aws_vm_data_disk_managed }}"
    cornerstone_vm_data_disk_size: "{{ item.value.cornerstone_vm_data_disk_size }}"
    cornerstone_vm_location: "{{ item.value.cornerstone_vm_location }}"
    cornerstone_working_dir: "{{ item.value.cornerstone_working_dir }}"
    cornerstone_vm_libvirt_template: "{{ item.value.cornerstone_vm_libvirt_template }}"
    cornerstone_vm_libvirt_file_type: "{{ item.value.cornerstone_vm_libvirt_file_type }}"
    cornerstone_vm_libvirt_vmtype: "{{ item.value.cornerstone_vm_libvirt_vmtype }}"
    cornerstone_vm_libvirt_vmos: "{{ item.value.cornerstone_vm_libvirt_vmos }}"
    cornerstone_vm_libvirt_vmmem: "{{ item.value.cornerstone_vm_libvirt_vmmem }}"
    cornerstone_vm_libvirt_vmcores: "{{ item.value.cornerstone_vm_libvirt_vmcores }}"
    cornerstone_vm_subnet: "{{ item.value.cornerstone_vm_subnet }}"
    cornerstone_vm_gateway: "{{ item.value.cornerstone_vm_gateway }}"
    cornerstone_vm_dns1: "{{ item.value.cornerstone_vm_dns1 }}"
    cornerstone_vm_dns2: "{{ item.value.cornerstone_vm_dns2 }}"
    cornerstone_vm_ip: "{{ item.value.cornerstone_vm_ip }}"
    cornerstone_vmware_validate_certs: "{{ item.value.cornerstone_vmware_validate_certs }}"
    cornerstone_vmware_hostname: "{{ item.value.cornerstone_vmware_hostname }}"
    cornerstone_vmware_username: "{{ item.value.cornerstone_vmware_username }}"
    cornerstone_vmware_password: "{{ item.value.cornerstone_vmware_password }}"
    cornerstone_vmware_datacenter: "{{ item.value.cornerstone_vmware_datacenter }}"
    cornerstone_vmware_vcsfolder: "{{ item.value.cornerstone_vmware_vcsfolder }}"
    cornerstone_vmware_instance_guest_id: "{{ item.value.cornerstone_vmware_instance_guest_id }}"
  with_dict: "{{ guests }}"
  tags: ["{{ cornerstone_platform }}"]

# EOF
